### ISSUE TITLE
数据咨询

### ISSUE THREAD

**Issue by zhangatao** [youzanai/trexpark#2]
你好，很感谢你们开源中文的clip模型，请问你们做clip的预训练模型，数据量级方便说一下吗

**Comment by rui-liu** [comment]
感谢关注！训练Clip模型我们使用了700万商品的图片和标题，覆盖几乎所有有赞类目。

**Comment by zhangatao** [comment]
感谢回复，再次感谢你们能开源商品相关的clip模型。
